### ISSUE TITLE
How can I use par2ls?

### ISSUE THREAD

**Issue by sanderjo** [jmoiron/par2ools#3]
How can I use par2ls? I tried the below, but no result

```
sander@witte:~/git/par2ools$ python
Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 9.2.1 20191008] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import par2ools
>>> dir(par2ools)
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__']
>>> par2ls
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'par2ls' is not defined
>>> 
>>> import par2ools.par2ls
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named par2ls
>>> import parls
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named parls
>>> import par2ls
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named par2ls
>>> from par2ools import par2ls
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name par2ls
>>> 

>>> dir(par2ools.__builtins__)
['__class__', '__cmp__', '__contains__', '__delattr__', '__delitem__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'has_key', 'items', 'iteritems', 'iterkeys', 'itervalues', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values', 'viewitems', 'viewkeys', 'viewvalues']
>>> dir(par2ools.__doc__)
['__class__', '__delattr__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
>>> 


```

**Comment by sanderjo** [comment]
Oh, wait ... `par2ls` is a CLI tool, not a python module / function?

```
$ par2ls blabla.vol000+02.par2
some_opensource_mp4.part1.rar
some_opensource_mp4.part2.rar
some_opensource_mp4.part3.rar
some_opensource_mp4.part5.rar
some_opensource_mp4.part6.rar
some_opensource_mp4.part4.rar
some_opensource_mp4.part7.rar
some_opensource_mp4.part1.rar
some_opensource_mp4.part2.rar
some_opensource_mp4.part3.rar
some_opensource_mp4.part5.rar
some_opensource_mp4.part6.rar
some_opensource_mp4.part4.rar
some_opensource_mp4.part7.rar
```
